In [1]:
from keras.datasets import reuters
(train_data,train_labels),(test_data,test_labels)=reuters.load_data(num_words=10_000)

2021-12-17 17:43:48.067355: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-17 17:43:48.067401: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [3]:
len(train_data)
len(test_data)

2246

In [ ]:
train_data[10]

In [10]:
word_index= reuters.get_word_index()
print(len(word_index))
print(type(word_index))
#word_index

30979
<class 'dict'>


In [ ]:
revers_word_index=dict([(value,key) for (key,value) in word_index.items()])
revers_word_index

In [18]:
decoded_news=' '.join([revers_word_index.get(i-3,'?') for i in train_data[25]])
decoded_news

"? there were 106 200 tonnes of u s corn shipped to the soviet union in the week ended march 26 according to the u s agriculture department's latest export sales report there were no wheat or soybean shipments during the week the ussr has purchased 2 65 mln tonnes of u s corn as of march 26 for delivery in the fourth year of the u s ussr grain agreement total shipments in the third year of the u s ussr grains agreement which ended september 30 amounted to 152 600 tonnes of wheat 6 808 100 tonnes of corn and 1 518 700 tonnes of soybeans reuter 3"

In [33]:
train_data[12]


[1,
 2,
 81,
 8,
 16,
 625,
 42,
 120,
 7,
 1679,
 1928,
 4,
 270,
 5,
 4,
 49,
 27,
 1299,
 381,
 2,
 231,
 81,
 4,
 120,
 1343,
 13,
 2,
 6,
 343,
 10,
 2568,
 334,
 116,
 13,
 137,
 5,
 25,
 335,
 80,
 28,
 10,
 96,
 5,
 272,
 15,
 90,
 67,
 7,
 197,
 2,
 5132,
 7,
 2450,
 2521,
 7112,
 6870,
 9,
 2,
 573,
 1259,
 2,
 75,
 8,
 17,
 12]

In [25]:
import numpy as np
np.unique(train_labels)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [34]:
def vectorize_sequences(metinler,dimension=10_000):
    results = np.zeros((len(metinler),dimension))
    for i,kelime in enumerate(metinler):
        results[i,kelime]=1.
    return results
    

In [36]:
x_train = vectorize_sequences(train_data)
x_train[5]

array([0., 1., 0., ..., 0., 0., 0.])

In [37]:
x_test = vectorize_sequences(test_data)

In [42]:
from keras.utils.np_utils import to_categorical
y_train =to_categorical(train_labels)
y_test =to_categorical(test_labels)
y_test[1000]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [43]:
from keras import models
from keras import layers

In [ ]:
model = models.Sequential()

In [45]:
model.add(layers.Dense(64,activation="relu",input_shape=(10_000,)))
model.add(layers.Dense(64,activation="relu"))
model.add(layers.Dense(46,activation="softmax"))

In [46]:
model.compile(optimizer="rmsprop",loss="categorical_crossentropy",metrics=["accuracy"])

In [48]:
x_val = x_train[:1000]
partial_x_train=x_train[1000:]
y_val=y_train[:1000]
partial_y_train=y_train[1000:]
print(len(x_val))
print(len(partial_x_train))

1000
7982


In [49]:
history = model.fit(partial_x_train,partial_y_train,epochs=2,batch_size=512, validation_data=(x_val,y_val))

2021-12-17 19:37:47.731172: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 319280000 exceeds 10% of free system memory.


Epoch 1/2
16/16 [==============================] - 39s 642ms/step - loss: 2.5246 - accuracy: 0.5333 - val_loss: 1.6837 - val_accuracy: 0.6560
Epoch 2/2
16/16 [==============================] - 1s 91ms/step - loss: 1.3418 - accuracy: 0.7204 - val_loss: 1.2752 - val_accuracy: 0.7220
